### ISSUE TITLE
CSS-Demo：按钮动画

### ISSUE THREAD

**Issue by OzzieNicholas** [OzzieNicholas/Blog#2]
### demo说明
1. 这部分 demo 有7个小部分，对应7种变化效果，html 如下：
```html
<!-- 整体背景渐变 -->
<button class="btn-1">按钮一</button>
<!-- 从左至右渐变 -->
<button class="btn-2">按钮二</button>
<!-- 从右至左渐变 -->
<button class="btn-3">按钮三</button>
<!-- 从上至下渐变 -->
<button class="btn-4">按钮四</button>
<!-- 从下至上渐变 -->
<button class="btn-5">按钮五</button>
<!-- 横向渐变 -->
<button class="btn-6">按钮六</button>
<!-- 纵向渐变 -->
<button class="btn-7">按钮七</button>
```
2. 这7中变化都有一个公共的 css 样式，是基础样式，如下：
```css
/* button 公共样式 */
button{
  position: relative;
  width: 100px;
  height: 40px;
  border: 1px solid #46b0ff;
  background: none;
  cursor: pointer;
}
button:after{
  position: absolute;
  content: '';
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
}
```
	+ 之后提到省略公共样式则为此部分

### 整个背景渐变
```css
/* 省略 button 公共样式 */
.btn-1:after{
  opacity: 0; 
  background: #46b0ff;
  transition: all .3s;
  z-index: -1;
}
.btn-1:hover:after{
  opacity: 1; 
}
```
1. 这里用相对定位和绝对定位来配合，利用伪类来作为鼠标的 `:hover` 事件
	+ 注意：使用绝对定位的元素，其父元素一定要使用相对定位，否则该元素会一直找相对定位的元素，直至根节点
2. 用 `transition` 来对 `:hover` 事件进行描述，规定 0.3s 完成动画，改变 `:after` 的透明度，`all` 是指所有行为均遵循此规则
3. 实际上，如果单单是为了实现 hover 样式，我们可以更简洁地写：
	```css
	button{
	  position: relative;
	  width: 100px;
	  height: 40px;
	  border: 1px solid #46b0ff;
	  background: none;
	  cursor: pointer;
	  background: rgba(70, 176, 255, 0);  /* 设置为完全透明 */
	  transition: all .3s;
	}
	.btn-1:hover{
	  background: rgba(70, 176, 255, 1);  /* 设置为不透明 */
	}
	```

### 从左至右
+ 我们在示例一的基础上，更进一步，如下：
```css
/* 省略 button 公共样式 */
.btn-2:after{
  width: 0;
  background: #f13f84;
  transition: all .3s;
  z-index: -1;
}
.btn-2:hover:after{
  width: 100%;
}
```

### 从右至左
```css
/* 省略 button 公共样式 */
.btn-3:after{
  width: 0;
  background: #00b7a3;
  transition: all .3s;
  z-index: -1;
  right: 0;
  left: initial
}
.btn-3:hover:after{
  width: 100%;
}
```

### 从上至下
```css
/* 省略 button 公共样式 */
.btn-4:after{
  height: 0;
  background: #00b7a3;
  transition: all .3s;
  z-index: -1;
  top: 0;
  bottom: initial
}
.btn-4:hover:after{
  height: 100%;
}
```

### 从下至上
```css
/* 省略 button 公共样式 */
.btn-5:after{
  height: 0;
  background: #00b7a3;
  transition: all .3s;
  z-index: -1;
  bottom: 0;
  top: initial
}
.btn-5:hover:after{
  height: 100%;
}
```

### 横向展开
```css
/* 省略 button 公共样式 */
.btn-6:after{
  width: 0;
  background: #ff9900;
  transition: all .3s;
  z-index: -1;
  left: 50%;
  transform: translateX(-50%);
}
.btn-6:hover:after{
  width: 100%;
}
```

### 纵向展开
```css
/* 省略 button 公共样式 */
.btn-7:after{
  height: 0;
  background: #00b7a3;
  transition: all .3s;
  z-index: -1;
  top: 50%;
  transform: translateY(-50%);
}
.btn-7:hover:after{
  height: 100%;
}
```
