### ISSUE TITLE
快速学习 Scss

### ISSUE THREAD

**Issue by OzzieNicholas** [OzzieNicholas/Blog#80]
## Sass 与 Scss

1. sass 是成熟、稳定、强大的CSS预处理器，而 scss 是 sass3 引入的新语法，它的语法完全兼容 css3，且继承了 sass 的强大功能，也就是说，任何标准的 css3 样式表都是具有相同语义的有效的 scss 文件，详情解释请查：[Sass — 语法](https://sass.bootcss.com/documentation/syntax)
2. scss 与 sass 的区别：
   + 先有 sass，之后才有 scss
   + scss 需要 `{}` 以及 `;`，而 sass 什么都不用，通过缩进来区分代码，类似于 `yaml` 语言

---

## 准备工作

1. scss 需要编译为 css 才能被浏览器识别，此处仅仅为小 demo 的学习，所以直接用 webpack 编译

2. 初始化：

   ```
   npm init -y
   ```

3. 安装 css-loader、style-loader、node-sass、sass-loader：

   ```
   npm install css-loader style-loader node-sass sass-loader --save-dev
   ```

4. 安装 webpack、webpack-cli：

   ```
   npm install webpack webpack-cli --save-dev
   ```

5. 配置文件：新建 `webpack.config.js`，内容如下：

   ```js
   // webpack.config.js
   const path = require('path')
   module.exports = {
       entry: './main.js',
       output: {
           filename: 'bundle.js',
           path: path.resolve(__dirname, 'dist')
       },
       module: {
           rules: [{
               test: /\.scss/,
               use: ['style-loader', 'css-loader', 'sass-loader']
           }]
       },
       mode: 'production'
   }
   ```

6. 新建 `dist` 文件夹，用于存放 `bundle.js`

7. 新建 `index.html` 如下：

   ```html
   <!DOCTYPE html>
   <html lang="en">
   <head>
       <meta charset="UTF-8">
       <meta name="viewport" content="width=device-width, initial-scale=1.0">
       <title>Document</title>
   </head>
   <body>
       <div id="global">Hello Scss</div>
       <script src="./dist/bundle.js"></script>
   </body>
   </html>
   ```

8. 新建 `style.scss` 如下：

   ```scss
   // 定义全局样式
   $global-color: red;
   // 使用变量
   #global {
       color: $global-color;
   }
   ```

9. 新建 `main.js` 如下：

   ```js
   import './style.scss'
   ```

10. 启动项目：

    ```
    npx webpack
    ```

    + 打开 `index.html`，查看结果，若文字为红色，则准备工作完成啦

### 变量

1. scss 中的变量用 `$` 标志，可以在变量中存储颜色、字体等任意的 css 值，写法为：

   ```scss
   $ 变量名: 变量值
   ```

2. scss 的变量是有作用域的，内部声明的变量无法在外部使用，除非在变量值后面添加 `!global` 声明

   + 还可以通过添加 `!default` 给变量设置默认值，这个在写一个样式库的时候比较实用，避免别人在没有给变量赋值之前使用

3. 案例分析：

   ```scss
   $btn-color: red;  // 声明变量（全局均可使用）
   $btn-color: blue;  // 同一变量，会被再次赋值
   #btn {
       $btn-font-size: 14px;  // 声明变量（#btn 才可使用）
       color: $btn_color;  // 使用全局变量
       font-size: $btn-font-size;  // 使用全局变量
   }
   ```

   编译后的 css 结果：

   ```css
   #btn {
       color: blue;
       font-size: 14px;
   }
   ```

4. 变量名中使用中划线或者下划线都是同一变量

5. scss 的变量有点类似 ES5 中的 var，同一变量可以被反复赋值

### 嵌套

1. scss 可以嵌套选择器，有点类似于 html 的嵌套结构，在嵌套规则中可以写任何 css 代码，包括群组选择器 `,`、子代选择器 `>`、同层相邻组合选择器 `+`、同层全体组合选择器`~` 等等，例如下面这个网站导航样式：

   ```scss
   nav {
       ul {
           margin: 0;
           padding: 0;
           list-style: none;
       }
       li {
           display: inline-block;
       }
       a {
           display: block;
           padding: 6px 12px;
           text-decoration: none;
       }
   }
   ```

   对应的 css：

   ```css
   nav ul {
       margin: 0;
       padding: 0;
       list-style: none;
   }
   
   nav li {
       display: inline-block;
   }
   
   nav a {
       display: block;
       padding: 6px 12px;
       text-decoration: none;
   }
   ```

2. 案例分析 — 嵌套的强大功能：

   + 先看原 scss：

     ```scss
     .container ul {
         border: 1px solid #aaa;
         list-style: none;
     }
     
     .container ul:after {
         display: block;
         content: "";
         clear: both;
     }
     
     .container ul li {
         float: left;
     }
     
     .container ul li>a {
         display: inline-block;
         padding: 6px 12px;
     }
     ```

   + 嵌套选择器：

     ```scss
     // 我们可以将子元素合并：
     
     .container ul {
         border: 1px solid #aaa;
         list-style: none;
         li {
             float: left;
         }
         li>a {
             display: inline-block;
             padding: 6px 12px;
         }
     }
     
     .container ul:after {
         display: block;
         content: "";
         clear: both;
     }
     ```

   + 嵌套父选择器：

     ```scss
     // 我们可以将公共的父元素提取出来：
     
     // 在 scss 中要用 & 表示当前元素的父元素
     .container ul {
         border: 1px solid #aaa;
         list-style: none;
         li {
             float: left;
         }
         li>a {
             display: inline-block;
             padding: 6px 12px;
         }
         // & 表示的是当前元素 ul 的父元素 .container
         &:after {
             display: block;
             content: "";
             clear: both;
         }
     }
     ```

     + 需要注意的是，只能在嵌套内部使用父级选择器，否则SCSS找不到父级元素会直接报错

   + 嵌套组合选择器：

     ```scss
     // 我们可以将子选择器和父选择器组合嵌套，将自带的选择器简化掉：
     
     .container ul {
         border: 1px solid #aaa;
         list-style: none;
         li {
             float: left;
             >a {
                 display: inline-block;
                 padding: 6px 12px;
             }
         }
         &:after {
             display: block;
             content: "";
             clear: both;
         }
     }
     ```

     + 子代选择器也可以写在外层选择器的右边：

       ```scss
       li> {
           a {
               display: inline-block;
               padding: 6px 12px;
           }
       }
       ```

       + 注意，这种写法会作用于所有嵌套的选择器上，尽量不要采用这类写法，扩展性不强，也容易出错。

3. 嵌套属性：

   ```scss
   // 原 scss：
   li {
       border: 1px solid #aaa;
       border-left: 0;
       border-right: 0;
   }
   
   // 将属性合并：
   li {
       border:1px solid #aaa {
           left: 0;
           right: 0;
       }
   }
   ```

   + 以分号 `;` 结尾的判断为一个属性，以大括号 `{}` 结尾的则判断为一个嵌套属性，规则是将外部的属性以及内部的属性通过中划线连接起来形成一个新的属性

### 引入

1. 在 css 中，我们是通过 `@import` 实现在一个 css 文件内部导入另一个 css 文件的，但是浏览器只有在执行到 @import 语句时才会去加载对应的 css 文件，css 原生的 @import 会通过额外的 HTTP 请求获取引入的样式片段，导致了性能变差，但是 scss 的 @import 并不会产生新的 HTTP 请求。

2. scss 通过 @import 将多个文件结合到一起，这意味着你可以按照功能将众多的 scss 文件拆分，使其结构化，例如，你可以分成：变量类、列表类、按钮类等等

   + 拆分成多个文件的时候，若文件是以 `_` 开头的，也不会被自动编译成 css，因为 scss 会通过下划线来辨别哪些是 scss 片段，从而只是在使用 @import 的地方才会导入

   + 例如，下面这个项目目录中，我的目的是将以 `_` 开头 scss 文件整合到 `result.css` 中：

     ```
     |-style
     	|- _a.scss
     	|- _b.scss
     	|- _c.scss
     	|- result.css
     ```

     ```scss
     // a.scss
     
     $color_1: red;
     $color-2: blue;
     ```

     ```scss
     // b.scss
     
     @import '_a';
     .btn {
         display: inline-block;
         padding: 3px 6px;
         background-color: $color_1; 
         color: $color_2;
     }
     ```

     生成的 css：

     ```css
     .btn {
         display: inline-block;
         padding: 3px 6px;
         background-color: red;
         color: blue;
     }
     ```

3. 导入变量的优先级问题：变量默认值

   + 在导入样式后，可能会出现变量值覆盖的问题，但若我们不想该变量被覆盖，则需要在最开始就加上默认的标志 `!default`

4. 嵌套导入：你同样可以在嵌套中使用导入（老千层饼了），那么导入的内容将只在局部引入
